-- MySQL Script generated by MySQL Workbench
-- Wed Sep 10 16:13:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siona_pos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siona_pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siona_pos` DEFAULT CHARACTER SET utf8 ;
USE `siona_pos` ;

-- -----------------------------------------------------
-- Table `siona_pos`.`empresa_tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`empresa_tenant` (
  `idempresa_tenant` INT(11) NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(13) NULL DEFAULT NULL,
  `nombre_comercial` VARCHAR(100) NULL DEFAULT NULL,
  `razon_social` VARCHAR(150) NULL DEFAULT NULL,
  `direccion_matriz` VARCHAR(150) NULL DEFAULT NULL,
  `actividad_economica` VARCHAR(200) NULL DEFAULT NULL,
  `tipo_contibuyente` ENUM('Persona natural', 'Persona juridica') NULL DEFAULT 'Persona natural',
  `regimen` ENUM('Regimen general', 'Rimpe negocio popular', 'Rimpe emprendedor') NULL DEFAULT 'Regimen general',
  `contabilidad` TINYINT(4) NULL DEFAULT 0,
  `agente_retencion` TINYINT(4) NULL DEFAULT 0,
  `contribuyente_especial` TINYINT(4) NULL DEFAULT 0,
  `artesano` TINYINT(4) NULL DEFAULT 0,
  `numero_calificacion_artesanal` VARCHAR(13) NULL DEFAULT NULL,
  `telefono` VARCHAR(13) NULL DEFAULT '0999999999',
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `correo_envio_factura` VARCHAR(150) NULL DEFAULT NULL,
  `ambiente_sri` ENUM('Pruebas', 'Produccion') NULL DEFAULT 'Pruebas',
  `password_correo_envio_factura` VARCHAR(50) NULL DEFAULT NULL,
  `puerto_correo_envio_factura` VARCHAR(5) NULL DEFAULT NULL,
  `servidor_smtp_correo_envio_factura` VARCHAR(45) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idempresa_tenant`),
  INDEX `idx_empresa_ruc` (`ruc` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `tenant_id` INT(11) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_empresa_tenant1_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `idx_tenant_categoria` (`tenant_id` ASC) VISIBLE,
  INDEX `idx_tenant_estado` (`tenant_id` ASC, `estado` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_empresa_tenant1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `siona_pos`.`empresa_tenant` (`idempresa_tenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_identificacion_sri` ENUM('04', '05', '06', '07', '08') NULL DEFAULT NULL,
  `numero_identificacion` VARCHAR(20) NULL DEFAULT NULL,
  `nombres` VARCHAR(150) NULL DEFAULT NULL,
  `apellidos` VARCHAR(150) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `tenant_id` INT(11) NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_clientes_empresa_tenant1_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `idx_cliente_tenant_identificacion` (`tenant_id` ASC, `numero_identificacion` ASC) VISIBLE,
  INDEX `idx_cliente_nombres` (`nombres` ASC, `apellidos` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_empresa_tenant1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `siona_pos`.`empresa_tenant` (`idempresa_tenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`sucursal` (
  `idsucursal` INT(11) NOT NULL AUTO_INCREMENT,
  `sri_codigo` VARCHAR(3) NULL DEFAULT '001',
  `sri_nombre` VARCHAR(150) NULL DEFAULT NULL,
  `sri_direccion` VARCHAR(150) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `tenant_id` INT(11) NOT NULL,
  PRIMARY KEY (`idsucursal`),
  INDEX `fk_sucursal_empresa_tenant_idx` (`tenant_id` ASC) VISIBLE,
  CONSTRAINT `fk_sucursal_empresa_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `siona_pos`.`empresa_tenant` (`idempresa_tenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`punto_de_emision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`punto_de_emision` (
  `idpunto_de_emision` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_sri` VARCHAR(3) NULL DEFAULT '001',
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `secuencial_factura` INT(11) NULL DEFAULT 1,
  `secuencial_nota_credito` INT(11) NULL DEFAULT 1,
  `secuencial_nota_debito` INT(11) NULL DEFAULT 1,
  `secuencial_guia_remision` INT(11) NULL DEFAULT 1,
  `secuencial_retencion` INT(11) NULL DEFAULT 1,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `sucursal_idsucursal` INT(11) NOT NULL,
  PRIMARY KEY (`idpunto_de_emision`),
  UNIQUE INDEX `unique_codigo_sucursal` (`codigo_sri` ASC, `sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_puntos_de_emision_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  CONSTRAINT `fk_puntos_de_emision_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `siona_pos`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT 'Quito',
  `telefono` VARCHAR(13) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `rol` ENUM('Administrador', 'Vendedor', 'Visualizador') NULL DEFAULT 'Administrador',
  `thumbnail` VARCHAR(255) NULL DEFAULT 'default',
  `created_at` DATETIME NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `sucursal_idsucursal` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  INDEX `idx_usuario_email` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `siona_pos`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`factura` (
  `idfactura` INT(11) NOT NULL AUTO_INCREMENT,
  `clave_de_acceso` VARCHAR(49) NULL DEFAULT NULL,
  `numero` VARCHAR(17) NULL DEFAULT NULL,
  `subtotal_0` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_12` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_14` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_15` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_5` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_no_objeto_impuesto` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_excento_iva` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_iva_diferenciado` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `subtotal_13` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_0` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_12` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_14` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_15` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_5` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_no_objeto_impuesto` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_excento_iva` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_diferenciado` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `iva_13` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `ice` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `total` DECIMAL(10,5) NULL DEFAULT NULL,
  `descuento` DECIMAL(10,5) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `metodo_pago` ENUM('01', '15', '16', '17', '18', '19', '20', '21') NULL DEFAULT '01',
  `anular_sri` TINYINT(4) NULL DEFAULT 0,
  `estado_sri` VARCHAR(20) NULL DEFAULT NULL,
  `estado_factura` ENUM('Borrador', 'Emitida', 'Autorizada', 'Anulada') NULL DEFAULT 'Emitida',
  `mensaje_sri` TEXT NULL DEFAULT NULL,
  `tiene_nota_credito` TINYINT(4) NULL DEFAULT NULL,
  `numero_nota_credito` VARCHAR(17) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `puntos_de_emision_idpunto_de_emision` INT(11) NOT NULL,
  `clientes_idcliente` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_factura_puntos_de_emision1_idx` (`puntos_de_emision_idpunto_de_emision` ASC) VISIBLE,
  INDEX `fk_factura_clientes1_idx` (`clientes_idcliente` ASC) VISIBLE,
  INDEX `fk_factura_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `idx_factura_numero` (`numero` ASC) VISIBLE,
  INDEX `idx_factura_clave_acceso` (`clave_de_acceso` ASC) VISIBLE,
  INDEX `idx_factura_fecha` (`fecha` ASC) VISIBLE,
  CONSTRAINT `fk_factura_clientes1`
    FOREIGN KEY (`clientes_idcliente`)
    REFERENCES `siona_pos`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_puntos_de_emision1`
    FOREIGN KEY (`puntos_de_emision_idpunto_de_emision`)
    REFERENCES `siona_pos`.`punto_de_emision` (`idpunto_de_emision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `siona_pos`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(12) NULL DEFAULT NULL,
  `codigo_auxiliar` VARCHAR(25) NULL DEFAULT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `precio_de_venta` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `precio_de_compra` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `tiene_descuento` TINYINT(4) NULL DEFAULT 0,
  `descuento_por_cantidad` INT(11) NULL DEFAULT 0,
  `precio_con_descuento` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `maneja_stock` TINYINT(4) NULL DEFAULT 0,
  `stock_actual` INT(11) NULL DEFAULT 0,
  `stock_minimo` INT(11) NULL DEFAULT 0,
  `stock_maximo` INT(11) NULL DEFAULT 0,
  `unidad_medida` VARCHAR(20) NULL DEFAULT 'Unidad',
  `peso` DECIMAL(8,3) NULL DEFAULT 0.000,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_producto` ENUM('Producto', 'Servicio') NULL DEFAULT 'Producto',
  `graba_iva` TINYINT(4) NULL DEFAULT 1,
  `porcentaje_iva` DECIMAL(5,2) NULL DEFAULT 15.00,
  `graba_ice` TINYINT(4) NULL DEFAULT 0,
  `porcentaje_ice` DECIMAL(5,2) NULL DEFAULT 0.00,
  `es_material_construccion` TINYINT(4) NULL DEFAULT 0,
  `codigo_material_construccion` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `categoria_idcategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `unique_codigo_tenant` (`codigo` ASC, `categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_productos_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  INDEX `idx_producto_codigo` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `siona_pos`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`factura_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`factura_detalle` (
  `idfactura_detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,3) NULL DEFAULT 1.000,
  `descripcion_producto` VARCHAR(150) NULL DEFAULT NULL,
  `precio_unitario` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `descuento` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `precio_sin_impuestos` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `created_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `factura_idfactura` INT(11) NOT NULL,
  `productos_idproducto` INT(11) NOT NULL,
  PRIMARY KEY (`idfactura_detalle`),
  INDEX `fk_factura_detalle_factura1_idx` (`factura_idfactura` ASC) VISIBLE,
  INDEX `fk_factura_detalle_productos1_idx` (`productos_idproducto` ASC) VISIBLE,
  INDEX `idx_detalle_factura` (`factura_idfactura` ASC) VISIBLE,
  INDEX `idx_detalle_producto` (`productos_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_factura_detalle_factura1`
    FOREIGN KEY (`factura_idfactura`)
    REFERENCES `siona_pos`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_detalle_productos1`
    FOREIGN KEY (`productos_idproducto`)
    REFERENCES `siona_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`login_attempts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `attempts` INT(11) NULL DEFAULT 1,
  `blocked_until` DATETIME NULL DEFAULT NULL,
  `last_attempt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `idx_ip_email` (`ip_address` ASC, `email` ASC) VISIBLE,
  INDEX `idx_blocked_until` (`blocked_until` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siona_pos`.`producto_por_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siona_pos`.`producto_por_sucursal` (
  `idproducto_sucursal` INT(11) NOT NULL AUTO_INCREMENT,
  `precio_sucursal` DECIMAL(10,5) NULL DEFAULT 0.00000,
  `stock_sucursal` INT(11) NULL DEFAULT 0,
  `stock_minimo_sucursal` INT(11) NULL DEFAULT 0,
  `stock_maximo_sucursal` INT(11) NULL DEFAULT 0,
  `estado` TINYINT(4) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `sucursal_idsucursal` INT(11) NOT NULL,
  `productos_idproducto` INT(11) NOT NULL,
  PRIMARY KEY (`idproducto_sucursal`),
  UNIQUE INDEX `unique_producto_sucursal` (`productos_idproducto` ASC, `sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_producto_por_sucursal_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_producto_por_sucursal_productos1_idx` (`productos_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_por_sucursal_productos1`
    FOREIGN KEY (`productos_idproducto`)
    REFERENCES `siona_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_por_sucursal_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `siona_pos`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
